### ISSUE TITLE
windows transparency is not active

### ISSUE THREAD

**Issue by hexavolta** [alexhulbert/nix#5]
first, i have to thank you for this beautiful  work of art ,it's a shame it doesn't have the fan base it deserves,maybe i have to point out that you have  provide a more detailed guide for installing the repository from scratch,i know Arch like the palm of my hand,but i don't know nothing about nix,so i struggled with some commands,finally after 2 failures i succeeded to  have your repository installed and everything works fine even the plasma elements,excepts for one thing " the windows transparency", the hypr-chroma plugin is enabled,all the  user services  all loaded and active except for hyprwatchd and kde-connect services.
Any suggestions please?
![2024-06-17-233833_hyprshot](https://github.com/alexhulbert/SeaGlass/assets/1753721/7627cb4f-a986-4b67-943a-1ee2cf6ccb76)

**Comment by alexhulbert** [comment]
Glad to hear someone else was able to get it working! Thank you for your kind words.

By the way, if you commit your changes to a fork, I'd be happy to throw some of the things you're not using behind a customizable flag so you can freely pull in changes when I make them. Thanks for the feedback about the nix stuff, too. I'm thinking I'll probably try to set it up from scratch in a VM in order to automate the setup as much as possible, but since you've already got it working, I'm open to whatever additional feedback you may have.

The issue you're facing with the transparency plugin is because of Hyprland's new 0.41 update. I'll update my plugin so that it works with the latest version of Hyprland later today.

**Comment by alexhulbert** [comment]
All set! I updated the plugin to support hyprland 0.41.1 and made some small nix adjustments to fix the broken services. If you pull in the changes and run `home-manager switch` + `hyprpm update`, everything should work. The only thing that's not working for me is copy+paste in the terminal, but I'm working on fixing that now.

I have hyprland and a few other dependent pkgs added to IgnorePkg in `/etc/pacman.conf` since hyprland updates pretty frequently and it takes a few days for plugin maintainers to get their plugins working with the latest version. I'll probably commit those changes to the repo soon.

**Comment by hexavolta** [comment]
thanks for responding,now  i have "plasma-waybar.service" failing to  start,resulting in  waybar icons being unusable (when i click on any of them the plasmoid doesn't show up)
![2024-06-18-204717_hyprshot](https://github.com/alexhulbert/SeaGlass/assets/1753721/10281ddc-0c98-465f-a42a-b0c8ea7001f9)

**Comment by hexavolta** [comment]
after  managing some permissions issues,everything works fine now,thank you.
